In [9]:
import csv

import numpy as np
import tensorflow as ts
from sklearn.model_selection import train_test_split

In [10]:
data = 'C:/Adatok/gesture_data.csv'

In [11]:
X_data = np.loadtxt(data, delimiter=',', dtype='float32', usecols=list(range(1, (21 * 2) + 1)))

In [12]:
X_data

array([[ 0.    ,  0.    ,  0.1219, ..., -0.6926, -0.1608, -0.7809],
       [ 0.    ,  0.    ,  0.1206, ..., -0.6888, -0.1608, -0.7745],
       [ 0.    ,  0.    ,  0.1206, ..., -0.6958, -0.1591, -0.785 ],
       ...,
       [ 0.    ,  0.    , -0.0643, ..., -0.7105,  0.1579, -0.7895],
       [ 0.    ,  0.    , -0.0546, ..., -0.7098,  0.1724, -0.7989],
       [ 0.    ,  0.    , -0.0616, ..., -0.6919,  0.1765, -0.7787]],
      dtype=float32)

In [13]:
X_data[0]

array([ 0.    ,  0.    ,  0.1219, -0.0742,  0.2191, -0.2173,  0.288 ,
       -0.3375,  0.3481, -0.4011,  0.1201, -0.5106,  0.1608, -0.6979,
        0.1802, -0.8163,  0.1943, -0.917 ,  0.0459, -0.5406,  0.0601,
       -0.7597,  0.0689, -0.894 ,  0.0724, -1.    , -0.0212, -0.523 ,
       -0.03  , -0.7244, -0.0336, -0.8498, -0.0371, -0.9576, -0.0866,
       -0.4611, -0.1201, -0.6007, -0.1431, -0.6926, -0.1608, -0.7809],
      dtype=float32)

In [14]:
y_data = np.loadtxt(data, delimiter=',', dtype='int32', usecols=(0))

In [15]:
y_data

array([1, 1, 1, ..., 3, 3, 3])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.25)

In [21]:
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam

In [22]:
X_train.shape

(1028, 42)

In [29]:
y_train.shape

(1028,)

In [31]:
# Define the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(42,)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(3, activation='softmax')  # 10 output neurons for 10 classes, softmax for multi-class classification
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [34]:
y_train_adjusted = y_train - 1
y_test_adjusted = y_test - 1

In [35]:
history = model.fit(x=X_train, y=y_train_adjusted, validation_data=(X_test, y_test_adjusted), batch_size=16, epochs=100)

Epoch 1/100
65/65 [==============================] - 1s 13ms/step - loss: 0.7947 - accuracy: 0.7558 - val_loss: 0.3582 - val_accuracy: 1.0000
Epoch 2/100
65/65 [==============================] - 0s 6ms/step - loss: 0.1403 - accuracy: 1.0000 - val_loss: 0.0279 - val_accuracy: 1.0000
Epoch 3/100
65/65 [==============================] - 0s 7ms/step - loss: 0.0160 - accuracy: 1.0000 - val_loss: 0.0075 - val_accuracy: 1.0000
Epoch 4/100
65/65 [==============================] - 1s 8ms/step - loss: 0.0060 - accuracy: 1.0000 - val_loss: 0.0036 - val_accuracy: 1.0000
Epoch 5/100
65/65 [==============================] - 0s 7ms/step - loss: 0.0033 - accuracy: 1.0000 - val_loss: 0.0022 - val_accuracy: 1.0000
Epoch 6/100
65/65 [==============================] - 1s 10ms/step - loss: 0.0023 - accuracy: 1.0000 - val_loss: 0.0014 - val_accuracy: 1.0000
Epoch 7/100
65/65 [==============================] - 1s 11ms/step - loss: 0.0014 - accuracy: 1.0000 - val_loss: 9.9823e-04 - val_accuracy: 1.0000
Epoch 